### ISSUE TITLE
Maintainer?

### ISSUE THREAD

**Issue by sandfoxme** [gugod/libravatar#12]
If you are no longer interested in developing this gem would you consider passing it to me or someone else as new maintainer? I thought of publishing a fork but keeping the original gem up and running is more preferable

**Comment by gugod** [comment]
Hi @sandfoxme !

Sorry I havn't noticed these notifications on github recently. I'm OK to release these gems for you, or to grant you the rights to release it (if possible).

**Comment by arokettu** [comment]
I see you have released 1.3.0
Thank you :)
I just thought it was completely abandoned
