### ISSUE TITLE
SRV discovery causes fatal error on non-standard port discovery

### ISSUE THREAD

**Issue by sunchaserinfo** [gugod/libravatar#7]
Case:
* libravatar 1.2.0
* ruby 2.0
* non-standard port in the SRV discovery
```_avatars-sec._tcp.sunchaser.info. 84463 IN SRV  0 0 8043 avatars.snch.pw.```
(not 443 for secure avatars)

Error:

no implicit conversion of Fixnum into String

libravatar (1.2.0) lib/libravatar.rb:87:in '+'
libravatar (1.2.0) lib/libravatar.rb:87:in 'get_base_url'
libravatar (1.2.0) lib/libravatar.rb:107:in 'to_s'
app/views/libravatar/test.html.erb:3:in '_app_views_libravatar_test_html_erb___3623993676016155218_69829426226360'

Fix:

libravatar.rb:87

change
```port_fragment = port != profile[:port] ? ':' + port : ''```
to
```port_fragment = port != profile[:port] ? ':' + port.to_s : ''```

**Comment by sandfoxme** [comment]
I integrated your patch to my fork - https://github.com/sandfoxme/libravatar

**Comment by sunchaserinfo** [comment]
@sandfoxme great
